[server]
port=8443
keep_alive=30
thread_count=4
max_connections=20
max_req_size=1048576
serve_file=./unit_tests_1.lua
sql_db_file=./server.db


[ssl]
cert_file=keys/cert.pem
key_file=keys/key.pem
# protocols: tlsv1.2; tlsv1.3; all; secure
iprotocols=secure
